### PR TITLE
extract pdf by pages (based on https://github.com/jrmuizel/pdf-extract/pull/73)

### PR DESCRIPTION
**Pull request by linusbierhoff**
I have added functionality to load an entire PDF, with each page separated. The code is based on the pull request mentioned in the title. I noticed there have been no updates since November 2023, so I attempted to contribute with these changes.

I apologize for the formatting changes by Clippy. My changes start at line 2197.

### CODE REVIEW

**Comment by jrmuizel** [comment]
Can you redo this without the formatting changes?

**Comment by linusbierhoff** [comment]
Done.

**Comment by linusbierhoff** [comment]
Is it possible to complete the merge request?

**Comment by linusbierhoff** [comment]
@jrmuizel Hi, can you please check if this pull request can be merged? Thanks!

**Pull request merged**
