### PR TITLE
re-export lopdf to prevent having to match the same lopdf version …

### PR DESCRIPTION
**Pull request by monkeydioude**
…on crate consumer's end + updated examples/extracr.rs

### CODE REVIEW

**Comment by monkeydioude** [comment]
Should I let the "extern" declarations be, to prevent breaking changes?

**Review by joepio — APPROVED** [review]
I think this is a good addition. Matching versions is a hassle

**Comment by joepio** [comment]
@jrmuizel I was considering making this a separate PR, too but it's already here

**Comment by prabirshrestha** [comment]
Hit this issue while working on [langchain-rust](https://github.com/Abraxas-365/langchain-rust/pull/202). Would be great if lopdf was exported.

**Comment by jrmuizel** [comment]
I did this in 91b91c54105e0ef6552a839faa1de3a146691403

**Comment by prabirshrestha** [comment]
Awesome. Would it be possible to release a new crate version?

**Pull request closed without merging**
